### ISSUE TITLE
--single flag for ipbb vivado make-project no longer functions

### ISSUE THREAD

**Issue by DavidMonk00** [ipbus/ipbb#109]
In the most recent tag, `dev/2020g`, the `--single` flag now requires a `TEXT` argument. It is not clear what this argument should be, as in `v0.5.2` this flag required no argument. Similarly the expected behaviour from `v0.5.2` cannot be reproduced in the newer version.

**Comment by alessandrothea** [comment]
Hi David, 
thanks for report. It's a bug indeed. 
Will fix it at the next chance,

Alessandro
