### ISSUE TITLE
Possible install failure

### ISSUE THREAD

**Issue by g-iles** [ipbus/ipbb#114]
I'm not sure if I'm doing something wrong, but after installation of ipbb-dev-2020g the command "which ipbb" fails despite removing earlier references to version 0.5.2 from the PATH.    Has the installation completed correctly?

[giles@greg-ryzen ~]$ which ipbb
/usr/bin/which: no ipbb in (/home/giles/ipbb-dev-2020g/tools/bin:/home/giles/ipbb-dev-2020g/venv/scripts:/home/giles/ipbb-dev-2020g/tests/scripts:/home/giles/.local/bin:/home/giles/bin:/home/giles/scripts:/opt/Xilinx/Vivado/2019.2/bin:/home/giles/.local/bin:/home/giles/bin:/usr/sue/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/opt/puppetlabs/bin:/opt/mentor/10.6a/modeltech/bin)

Commands run are the following:
curl -L https://github.com/ipbus/ipbb/archive/dev/2020g.tar.gz | tar xvz
source ipbb-dev-2020g/env.sh

Text file attached with the details.
[ipbb-woe.txt](https://github.com/ipbus/ipbb/files/5939155/ipbb-woe.txt)

**Comment by alessandrothea** [comment]
Hi Greg,
According to the console log the `v0.5.2` environment had been sourced first and `dev/2020g` on top of it.
I fear that the 2 venvs could interfere with each other. Can you try again, sourcing `ipbb-dev-2020g/env.sh` from a clean shell?

**Comment by g-iles** [comment]
Thanks - fixed.  In the end I just rebooted the PC andd now seems OK.
