### ISSUE TITLE
Master branch validation/debugging

### ISSUE THREAD

**Issue by alessandrothea** [ipbus/ipbb#121]
Hi all. I just tried out the `dev/2021a` tag. I encounter a similar, but different error to Giovanni in the simulation commands.
On `ipbb sim generate-project`, or in Python `from ipbb.cmds import sim` an error is thrown about [this import](https://github.com/ipbus/ipbb/blob/dev/2021a/src/ipbb/cmds/sim.py#L32): `from ._utils import ( #... some stuff`

[This line](https://github.com/ipbus/ipbb/blob/dev/2021a/src/ipbb/cmds/sim.py#L14) suggests what the import should be, but I didn't check.

Then turning this into a general question... is there a specific reason to use relative imports rather than absolute? It may help to avoid such bugs.
e.g. `from ..utils import # ...` -> `from ipbb.utils import`

_Originally posted by @thesps in https://github.com/ipbus/ipbb/issues/120#issuecomment-793552279_

**Comment by alessandrothea** [comment]
OK, thanks @thesps, patch coming up.
In cases of module relocation, like this one, absolute vs relative doesn't make much difference.

**Comment by alessandrothea** [comment]
Fix in `bugfix/utils_import`. Can you please give it a go?

**Comment by tswilliams** [comment]
> Fix in `bugfix/utils_import`. Can you please give it a go?

I just tried using this for the EMP CI, which covers parts of sim workflow (`setup-simlib`, `fli-eth` and `generate-project`), standard vivado build workflow, and `ipbb ipbus gendecoders`. No problems observed.

**Comment by tswilliams** [comment]
@thesps @gpetruc : Do the fixes in the `bugfix/utils_import` branch resolve all issues for you?

**Comment by thesps** [comment]
Hi, I just tested it and it does resolve the issue, thanks!
I don't think what I've been doing touches all the changes in that branch, but certainly the import fixes in src/ipbb/cmds/sim.py resolve the issue I saw.

**Comment by tswilliams** [comment]
Thanks for testing @thesps ! To avoid confusion: @gpetruc did you want to run any other tests, or is this commit fully functional from correlator perspective now?

**Comment by artlbv** [comment]
Hi, it seems I've encountered a similar issue, but just following the [walkthrough-1 Step 7](https://serenity.web.cern.ch/serenity/emp-fwk/walkthroughs/walkthrough1.html#step-7-build-the-firmware)

```bash
# uh2ml4l1 @ uh2clnmpcb4 in /scratch/emp-fwk/ipbb_area/algo-work/proj/my_algo [21:06:45] 
$ ipbb ipbus gendecoders                              
ERROR ('ModuleNotFoundError' exception caught): 'No module named 'ipbb.cmds._utils''

File "/scratch/emp-fwk/ipbb_area/ipbb-dev-2021a/src/ipbb/cmds/ipbus.py", line 11, in <module>
   from ._utils import DirSentry, formatDictTable
```

I just used the branch with the fix branch but now I get this error:
```bash
(ipbb) (base) 
# uh2ml4l1 @ uh2clnmpcb4 in /scratch/emp-fwk/ipbb_area/algo-work/proj/my_algo [21:22:38] 
$ ll
total 0
(ipbb) (base) 
# uh2ml4l1 @ uh2clnmpcb4 in /scratch/emp-fwk/ipbb_area/algo-work/proj/my_algo [21:22:39] 
$ ipbb ipbus gendecoders                                                                       
ERROR ('TypeError' exception caught): 'stat: path should be string, bytes, os.PathLike or integer, not NoneType'

File "/scratch/uh2ml4l1/anaconda3/lib/python3.8/genericpath.py", line 19, in exists
   os.stat(path)

```

I've printed the `print(ictx.currentproj.path) ` and it returns `None`.  
Any hints are appreciated!

**Comment by gpetruc** [comment]
> 
> 
> Thanks for testing @thesps ! To avoid confusion: @gpetruc did you want to run any other tests, or is this commit fully functional from correlator perspective now?

I'm running a test 
https://gitlab.cern.ch/cms-cactus/phase2/firmware/correlator-layer1/-/pipelines/2402692

**Comment by artlbv** [comment]
> Hi, it seems I've encountered a similar issue, but just following the [walkthrough-1 Step 7]

Never mind! I've recreated the work are using the fixed ipbus version and it seems to run without errors. Must have been a bug when fixing the ipbus version in the middle of the setup.

**Comment by gpetruc** [comment]
> 
> 
> > Thanks for testing @thesps ! To avoid confusion: @gpetruc did you want to run any other tests, or is this commit fully functional from correlator perspective now?
> 
> I'm running a test
> https://gitlab.cern.ch/cms-cactus/phase2/firmware/correlator-layer1/-/pipelines/2402692

looks ok for me
