### ISSUE TITLE
Cannot `pip install` dev/2021f

### ISSUE THREAD

**Issue by thesps** [ipbus/ipbb#139]
Hi, when I try to `pip install https://github.com/ipbus/ipbb/archive/dev/2021f.tar.gz` (or `c` through `e` tags as well)

I get an error:
```
ERROR: Cannot install ipbb and ipbb==1.0.0a1 because these package versions have conflicting dependencies.

The conflict is caused by:
    ipbb 1.0.0a1 depends on ipython==7.16.1
    ipdb 0.13.7 depends on ipython>=7.17.0; python_version > "3.6"
```

Just a small update to `requirements.txt` required I suppose.

**Comment by alessandrothea** [comment]
Hi @thesps,
I cannot reproduce the problem on CC7. What OS are you running on?

**Comment by alessandrothea** [comment]
Ah-ha! That explains it.
Unfortunately, the python version available on CC7 is 3.6, which doesn't allow switching to `ipython>=7.17.0`

**Comment by alessandrothea** [comment]
Hi, I have update the setuptool configuration in #145, splitting core dependencies from development tools like `ipdb` and `ipython`, which are causing trouble for you. Can you give it a go?
I've tagged version `dev/2021i` that should do the trick.

**Comment by thesps** [comment]
Thanks, it seems to install nicely now with this `dev/2021i` tag!
