### ISSUE TITLE
Use entity not called "top" as the top entity

### ISSUE THREAD

**Issue by tj710** [ipbus/ipbb#158]
Hi, 

Is it possible to do this and/or add support for this? 

I think that ipbb/depparser/VivadoProjectMaker.py does write('set_property top top [current_fileset]') which overwrites my custom settings from the setup tcl. 

Thanks a lot, 

Tom

**Comment by alessandrothea** [comment]
Hi Tom,

This is already supported in recent versions by setting the `top_entity` variable in your top dep file, e.g.

```
@top_entity = "my_top"
```

What ipbb version are you using?

**Comment by tj710** [comment]
Great, this works - I was using an older version and then after updating wasn't aware of the new @top_entity variable. Thanks!
