### ISSUE TITLE
Setting sim.library

### ISSUE THREAD

**Issue by thesps** [ipbus/ipbb#165]
I found that setting `@sim.library = 'xil_defaultlib'` in the dep file has no effect, the default simulation library remains `work`.

I think the issue is that [this line](https://github.com/ipbus/ipbb/blob/dev/2022c/src/ipbb/cmds/sim.py#L494):
```
SimLibrary = lDepFileParser.settings.get('{_toolset}.library', 'work')
``` 
should rather be:
```
SimLibrary = lDepFileParser.settings.get(f'{_toolset}.library', 'work')
``` 
(missing `f` for f-string formatting).

**Comment by alessandrothea** [comment]
Ouch. Used to work, I wonder where I lost that `f`...

**Comment by alessandrothea** [comment]
Fixed in `thea/bugfix_simlibrary`, hopefully
