### ISSUE TITLE
Generate Decoder files without IPBus Software

### ISSUE THREAD

**Issue by DavidMonk00** [ipbus/ipbb#212]
Would it be possible to remove the dependency of `ipbb ipbus gendecoders` on ipbus-software/uhal?

In CI pipelines or other containerised workflows, installing ipbus-software, particularly from source on non-yum based distros is a significant overhead for the need of a single command which is integral to IPBB workflows

Would it be possible to copy the functionality into IPBB directly?

**Comment by tswilliams** [comment]
Hi!

Although technically possible, this would involve duplicating the uHAL address table parsing logic, which beyond taking time implement initially would also increase the chance of bugs in the IPBB implementation. Even disregarding those factors though, the motivation for this isn't really clear to me: uHAL can be installed on non-RPM-based systems by running "make && make install". So for containerised FW builds I'd typically just install uHAL in the container image that's being used by the CI pipeline or similar (e.g. this is what I already do for the images that we use in the EMP and IPbus FW CI), and hence the need to build uHAL wouldn't affect the duration of the CI pipeline. As discussed in the CMS TkBES HW meeting just now though, maybe this is no longer an issue if uHAL is installed in all of the images created by the CERN `ci4fpga` group.

**Comment by DavidMonk00** [comment]
Hi Tom, thanks for the response. Whilst I agree it is possible to install UHAL into the base image to provide the functionality, from an architectural perspective, with CI widely used now, the software and machines used to build the firmware images (ipbb) is likely independent from those which control the FPGAs. IPBus software has a lot of dependencies (Erlang etc) which are not needed for the parsing of address tables, so it feels like a significant overhead to install the full software stack.

Alternatively, is it possible to have a "minimal" ipbus-software install that only provides the functionality used for building firmware, rather than running IPBus?

**Comment by tswilliams** [comment]
Indeed, Erlang wouldn't be required for uHAL (only for the ControlHub which, as you say, is not relevant for IPBB). You can skip that dependency by just installing the uHAL RPMs - or when building from source, adding `Set=uhal` to the `make` commands - then you'll only need boost & pugixml.

If building uHAL from source, you could also slightly speed up the build by skipping the test & GUI packages; this can be done by adding `BUILD_UHAL_TESTS=0 BUILD_UHAL_GUI=0` to the `make` command

**Comment by DavidMonk00** [comment]
Thank you, I will keep that in mind for future use!
