### ISSUE TITLE
Suggestion for dev/master: change default top-level dependency file to top.d3

### ISSUE THREAD

**Issue by jhegeman** [ipbus/ipbb#59]
Since one of the main goals of the dev/master branch is to switch to the new .d3 dependency file format, it would be nice to also switch the default value of the top-level dependency file from top.dep to top.d3.

**Comment by alessandrothea** [comment]
Hi,
Indeed. You're referring to the `ipbb proj create` command, aren't you?

**Comment by jhegeman** [comment]
Indeed, I am.

**Comment by alessandrothea** [comment]
I finally managed to have a look at the code. The tricky bit here is to maintain backward compatibility and still predictable behaviour. That means
- Transform the default top into a list of candidates `['top.d3', 'top.dep']` or basename + extensions `top`+`['.d3', '.dep']`
- Change the logic to require that one and only one of the candidates matches an existing file
- If zero or more than one matches are available, `proj create` shall request the user to specify the top.

Does this make sense to you, @jhegeman ?

**Comment by alessandrothea** [comment]
Note: this is part of the general migration from `dep` as unique dependency file format.
For consistency, the default extension file logic used by `DepFileParser` must be updated to allow matching both `<package>.dep` and `<package>.d3`

**Comment by jhegeman** [comment]
> I finally managed to have a look at the code. The tricky bit here is to maintain backward compatibility and still predictable behaviour. That means
> 
> * Transform the default top into a list of candidates `['top.d3', 'top.dep']` or basename + extensions `top`+`['.d3', '.dep']`
> * Change the logic to require that one and only one of the candidates matches an existing file
> * If zero or more than one matches are available, `proj create` shall request the user to specify the top.
> 
> Does this make sense to you, @jhegeman ?

Yes, that approach makes sense to me. That will be invisible for users who have not yet migrated, allow the new default for users who have migrated, and ask for confirmation for users who are half-way through their migration.

**Comment by alessandrothea** [comment]
Should be done in `feature/59_and_75`.
Can you give it a go, @jhegeman ?

**Comment by jhegeman** [comment]
Hi @alessandrothea,

Cool. This looks good. I tried it on a few different projects, and all looks good to me (as in: exactly as I hoped it would behave).

Cheers,
Jeroen

**Comment by alessandrothea** [comment]
Thanks

**Comment by jhegeman** [comment]
Crap. It looks as if in our enthusiasm we have broken something. I just started with a completely clean slate and now I run into this:

```
Unresolved files:
  +-----------------------------------------------------------------------------------------------------------------------------------+
  |                          path expression                                  package                 component           included by |
  +===================================================================================================================================+
  | cms-tcds2-firmware/projects/dth_p1v1_nodelpb/firmware/cfg/__auto__   cms-tcds2-firmware   projects/dth_p1v1_nodelpb   (top)       |
  +-----------------------------------------------------------------------------------------------------------------------------------+
```

This has snuck in via this commit:
  https://github.com/ipbus/ipbb/commit/4d2ae487d59f83cb7d8874382baeea282c841e1b

Jeroen

**Comment by alessandrothea** [comment]
Hm, =
`__auto__` is a placeholder injected by the cli layer, that should be detected by the `create` command implementation and resolved as a `.dep` or `.d3` file.
It should definitely not end up in `.ipbb_proj.yml`.

Is there a way for me to reproduce this? It would significantly speed up debugging.

Alessandro

**Comment by alessandrothea** [comment]
Alright, this was just me being stupid.
I did the hard bit and forgot to fix the easy one.
Should be fine now, in `bugfix/59`. Have a go at it and let me know how it goes, @jhegeman

**Comment by jhegeman** [comment]
That's what I thought. I just needed filling in the result of the search into the project dict. Thanks Alessandro!

**Comment by alessandrothea** [comment]
OK, I'll

**Comment by alessandrothea** [comment]
@jhegeman : new tag `dev/2020f`
