### ISSUE TITLE
Suggestion/request: rename bitfile and memcfg results with project name

### ISSUE THREAD

**Issue by jhegeman** [ipbus/ipbb#72]
Hi @alessandrothea 

As we discussed in our long-and-intermittent email thread: in my opinion it would be great if ipbb could rename the products of the bitfile and memcfg generation with the project name, just as it does with the package tarball.

An open question is whether is should do the renaming immediately after creation (which would be most consistent) or only at the 'ipbb package' stage.

The reasoning behind this request is as follows:

> All my designs are built for a unified architecture based around an infrastructure part, a system part, and a user part. The aim is to only change the user logic from design to design. This means that the top-level has been standardised, but since it has the same name in all designs also all designs lead to bit/bin files with the same name. Names that match the project names would be easier to track the results.

Cheers,
Jeroen

**Comment by alessandrothea** [comment]
Thanks. I hope to have a fix by the first half of next week.
Poke me if you don’t hear back from me.

**Comment by alessandrothea** [comment]
@jhegeman implemented in branch `feature/bitfile_name`. Can you give it a go?

**Comment by jhegeman** [comment]
Hi @alessandrothea,

Thanks. This one does what I was hoping for, indeed. Now one can influence the names of both the package tarball and the bit/bin files in a consistent way by choosing an appropriate project directory name.

Cheers,
Jeroen
