### ISSUE TITLE
Need support for xcix files

### ISSUE THREAD

**Issue by jhegeman** [ipbus/ipbb#73]
In addition to IP cores Xilinx supports 'IP core containers' with a .xcix extension. At the moment ipbb does not recognise such files, which leads to errors like the following (upon make-project):
```
make-project | add_files -norecurse -fileset None /afs/cern.ch/work/j/jhegeman/cms_tcds2/uhal/dth_ipbb/src/cms-tcds2-firmware/functions/dth/firmware/xci/gth_master_timing/gth_master_timing.xcix
make-project | CRITICAL WARNING: [Vivado 12-990] Fileset specified doesn't exist. Create it first using the create_fileset command.
make-project | ERROR: [Common 17-162] Invalid option value specified for '-fileset'.
```
This is because of the 'None' specified as fileset target, which is due to the fact that the .xcic file in the .d3 file is not recognised as ipbb-supported file type.

**Comment by alessandrothea** [comment]
Thanks for the report and the diagnosis.
Will fix it ASAP

**Comment by jhegeman** [comment]
In case it helps: based on Vivado's documentation I would expect that the IP core containers can be treated exactly like plain IP cores. A quick hack of my local ipbb installation seems to indicate that this indeed works. (I.e., I made the .xci and .xcix extensions equivalent throughout the ipbb code and the project builds.)

**Comment by alessandrothea** [comment]
It helps indeed. Thanks!

**Comment by alessandrothea** [comment]
@jhegeman implemented in `feature/xcix_support` branch.
Can you give it a go?

**Comment by jhegeman** [comment]
Hi @alessandrothea,

This seems to work. The Vivado project is created (and this was the step that previously failed) without complaints. I have not had time to actually build anything with the project, but I don't expect any issues here.

Cheers,
Jeroen
