### ISSUE TITLE
problems using setup.py

### ISSUE THREAD

**Issue by charles-armijo** [ipbus/ipbb#74]
We are working on the Atlas phase 2 upgrade.  
When using pip install https://github.com/ipbus/ipbb/archive/v0.5.2.tar.gz

The install exits with an error on IPdb.
The IPdb setup.py seems to call /usr/lilb64/python 2.7 and then complains that it must be python >=3.4

I was running the default /usr/bin/python linking to python3.  
I get the same message if I run the default python linking to python2.
Any ideas on how to get around this?   

Thanks, 
Charlie Armijo
University of Arizona Physics Dept.

Error message:
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting IPdb
  Using cached ipdb-0.13.3.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eIXDSD/IPdb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eIXDSD/IPdb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-t9OY16
         cwd: /tmp/pip-install-eIXDSD/IPdb/
    Complete output (3 lines):
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in ipdb setup command: Invalid environment marker: python_version >= "3.4"
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by alessandrothea** [comment]
Hi Charles,

Thanks for reporting the problem. This is probability happening because the dependency versions are not locked in `v0.5.3` as they are in `dev/master`.
Let me backport this feature.
I’ll have a branch for you to test soon, hopefully

**Comment by alessandrothea** [comment]
Hi again,

I haven't managed to reproduce the error so far. May I ask you what linux release are you using?
And what pip version is installed there (`pip --version`)
Could you also try setting up ipbb in virtualenv by doing:
```
curl -L https://github.com/ipbus/ipbb/archive/v0.5.2.tar.gz | tar xvz
source ipbb-v0.5.2/env.sh
```
and let me know how it goes?

**Comment by charles-armijo** [comment]
Hi,

Thanks for your quick response.  I'm running on centos 7.  The original try was with  the yum version of pip.  I upgraded to  pip 20.1.1.
I ran "curl -L https://github.com/ipbus/ipbb/archive/v0.5.2.tar.gz | tar xvz" with no problems.

Then I ran,
[root@eepp-altera ipbb]# source ipbb-v0.5.2/env.sh
bash: ipbb-v0.5.2/env.sh: No such file or directory

I went in and ran chmod +x on env.sh.  I tried to run as before and got the same result.  I went down one level and ran "./env.sh" with no problems.

I'm am not sure what the problem was.  However, I think I have the tools I need.  Thanks very much for your help.

Charlie Armijo
________________________________

**Comment by alessandrothea** [comment]
Glad to hear it's working.
My bet is `pip`. The system version of Centos7 is ancient and it's just incompatible with the the modern pip packages, I think.

Alessandro
