### ISSUE TITLE
Conflict in vivado options

### ISSUE THREAD

**Issue by jhegeman** [ipbus/ipbb#92]
The ```-o``` option is used for two different ```ipbb vivado``` options:

https://github.com/ipbus/ipbb/blob/9e266ca1bc2df8842d8427358c124e7c58e87180/src/ipbb/cli/vivado.py#L61

and

https://github.com/ipbus/ipbb/blob/9e266ca1bc2df8842d8427358c124e7c58e87180/src/ipbb/cli/vivado.py#L63

This is a conflict, but it seems to go unnoticed because the default for both `--optimize` and `--to-stdout` is true.

**Comment by alessandrothea** [comment]
Damn. It shall be fixed.
